<a href="https://colab.research.google.com/github/Suprio85/NLP/blob/main/Tokenizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install pandas numpy matplotlib transformers datasets

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.2/491.2 kB 8.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.9/183.9 kB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 6.8 MB/s eta 0:00:00
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.0
    Uninstalling fsspec-2025.3.0:
      Successfully uninstalled fsspec-2025.3.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2024.12.0 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 which is i

In [19]:
import numpy as np
import pandas as pd
from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoModelForCausalLM
from datasets import load_dataset

In [5]:
bts_dataset = "lamini/bts"
taylor_swift_dataset = "lamini/taylor_swift"

In [6]:
dataset_swiftie = load_dataset(taylor_swift_dataset)
train_data = pd.DataFrame(dataset_swiftie["train"])
train_data.head()

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


README.md:   0%|          | 0.00/573 [00:00<?, ?B/s]

(…)-00000-of-00001-54dd04266a81dbc7.parquet:   0%|          | 0.00/257k [00:00<?, ?B/s]

(…)-00000-of-00001-185d72ed4b72e469.parquet:   0%|          | 0.00/46.3k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/783 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/87 [00:00<?, ? examples/s]

question  \
0  What is the controversy surrounding Taylor Swi...   
1  What is the most popular Taylor Swift song amo...   
2  What is the significance of the album Red in T...   
3             What is Taylor Swift's favorite color?   
4                                      tay tay 4life   

                                              answer  \
0  Taylor Swift has been involved in several cont...   
1  Taylor Swift's "Shake It Off" is the most popu...   
2  Taylor Swift's album Red was released in 2012 ...   
3  Taylor Swift has expressed a fondness for the ...   
4                         Yes, Taylor Swift for life   

                                           input_ids  \
0  [1276, 310, 253, 16305, 8704, 11276, 24619, 43...   
1  [1276, 310, 253, 954, 4633, 11276, 24619, 4498...   
2  [1276, 310, 253, 8453, 273, 253, 5400, 4410, 2...   
3  [1276, 310, 11276, 24619, 434, 7583, 3295, 32,...   
4  [85, 333, 246, 333, 577, 8206, 4374, 13, 11276...   

                                      attention_mask  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
1  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
2  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
3  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
4               [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]   

                                              labels  
0  [1276, 310, 253, 16305, 8704, 11276, 24619, 43...  
1  [1276, 310, 253, 954, 4633, 11276, 24619, 4498...  
2  [1276, 310, 253, 8453, 273, 253, 5400, 4410, 2...  
3  [1276, 310, 11276, 24619, 434, 7583, 3295, 32,...  
4  [85, 333, 246, 333, 577, 8206, 4374, 13, 11276...

In [7]:
text = train_data["question"][0]
text

"What is the controversy surrounding Taylor Swift's music and how has it impacted her career?"

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("EleutherAI/pythia-70m")
model = AutoModelForSequenceClassification.from_pretrained("EleutherAI/pythia-70m")



In [25]:
encoded_text = tokenizer(text)['input_ids']
encoded_text

[5303, 612, 11, 1374, 389, 345, 30]

In [10]:
decoder = tokenizer.decode(encoded_text)
decoder

"What is the controversy surrounding Taylor Swift's music and how has it impacted her career?"

In [27]:
Questions = train_data["question"]
Answers = train_data["answer"]

questions =   Questions.tolist()
# questions



In [28]:
tokenizer.pad_token = tokenizer.eos_token
max_length = 128
tokenizer.truncation_side = 'left'
encoded_text = tokenizer(questions, padding=True,truncation=True, max_length=max_length)['input_ids']
# encoded_text

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("gpt2")
model = AutoModelForCausalLM.from_pretrained("gpt2")


In [30]:
text ="hi there, How are you?"
tokenizer.pad_token = tokenizer.eos_token
tokenizer.truncation_side = "left"
tokenizer.padding_side = "left"
encoded_text = tokenizer(text,padding=True,truncation=True,return_tensors="pt")
tokens  = tokenizer.tokenize(text)
ids = tokenizer.convert_tokens_to_ids(tokens)
tokens,ids,encoded_text['input_ids'] ,

(['hi', 'Ġthere', ',', 'ĠHow', 'Ġare', 'Ġyou', '?'],
 [5303, 612, 11, 1374, 389, 345, 30],
 tensor([[5303,  612,   11, 1374,  389,  345,   30]]))

In [32]:
import torch
output_1 = model(encoded_text['input_ids'])
output_2 = model(torch.tensor([ids]))
output_1[0],output_2[0]

(tensor([[[ -31.3108,  -31.0401,  -33.9539,  ...,  -38.7304,  -37.7306,
            -31.8250],
          [ -73.4507,  -73.8593,  -80.4965,  ...,  -85.0548,  -81.5502,
            -77.3155],
          [-104.7395, -105.5073, -107.5396,  ..., -108.1996, -106.1598,
           -103.1151],
          ...,
          [ -80.7800,  -82.1791,  -86.0961,  ...,  -85.2966,  -88.2991,
            -83.1623],
          [ -92.6335,  -95.0231, -101.0389,  ..., -103.1340, -103.8702,
            -98.0894],
          [-114.6349, -114.1608, -116.6036,  ..., -123.4321, -123.2473,
           -112.5469]]], grad_fn=<UnsafeViewBackward0>),
 tensor([[[ -31.3108,  -31.0401,  -33.9539,  ...,  -38.7304,  -37.7306,
            -31.8250],
          [ -73.4507,  -73.8593,  -80.4965,  ...,  -85.0548,  -81.5502,
            -77.3155],
          [-104.7395, -105.5073, -107.5396,  ..., -108.1996, -106.1598,
           -103.1151],
          ...,
          [ -80.7800,  -82.1791,  -86.0961,  ...,  -85.2966,  -88.2991,
         

In [33]:
tokenizer.decode(output_1.logits.argmax(dim=-1)[0])

', is and can you?\n'